In [12]:
l1=[1,2,3,4]
l2=[4,5,6,7]

new=zip(l1,l2)
print(new)

In [7]:
res=[]
for i in range(len(l1)):
    res.append((l1[i],l2[i]))
print(res)

[(1, 4), (2, 5), (3, 6), (4, 7)]


In [17]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [24]:
l=[1,2,3,4,5,6]

ar3=np.array(l)
ar4=ar3.reshape(2,3)
ar4

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr4=np.array([[1,2,3],[1,3,4]])
arr4

array([[1, 2, 3],
       [1, 3, 4]])

In [28]:
arr4.shape

(2, 3)

In [29]:
np.arange(1,13).reshape(4,6)

ValueError: cannot reshape array of size 12 into shape (4,6)

In [33]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
print("dimensions :",arr.ndim)
print("elements :",arr.size)
print("datatype :",arr.dtype)

dimensions : 2
elements : 9
datatype : int64


In [47]:
n1=np.arange(1,6)
n2=np.arange(6,11)
print(n1+n2)
print(n1*n2)
print(n1/n2)
print(n1%n2)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]


In [ ]:
a=np.array([1,"hi",True,9.89])
a.dtype

dtype('<U32')

In [53]:
m=np.ones((3,3),dtype="int32")
m.dtype
m

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [56]:
np.square(arr)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [57]:
np.abs(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
array=np.array(range(36)).reshape(6,6)
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [63]:
data=np.arange(6)
print(np.std(data))
print(np.var(data))

1.707825127659933
2.9166666666666665


In [65]:
m=np.mean(data)
std=np.std(data)
for i in data:
    print((i-m)/std)
    

-1.4638501094227998
-0.8783100656536799
-0.29277002188455997
0.29277002188455997
0.8783100656536799
1.4638501094227998


In [68]:
import maths_func as mf

print(mf.add(1,2.4))
print(mf.PI)

3.4
3.14


In [69]:
from maths_func import add
print(add(2,4))

6


In [82]:
aa=np.arange(12)
aa=np.pad(aa,(0,4),constant_values=1).reshape(4,4)
print(aa)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 1  1  1  1]]
